USE [PERSON ]
--USERS-----------------------------------------------------------------------------------
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Mohammad' ,'Zarei' , 'Babol' , 24 , 'MMDklojkoj@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Hossein' , 'Rezaii' , 'Mashhad' , 32 , 'HIUOHUYEM@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Arian' , 'Shajii' , 'Abadan' , 22 ,'RFEOUYOU@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Komeil' , 'Akbari' , 'Tehran' , 43 , 'Y4OIOPIUER@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Ali' , 'Mohammadi' , 'Yazd' , 39 , 'TML67509I@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Nika' ,'Salami', 'Tehran' , 27 , 'LKWFHERHES@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Zahra' , 'Vakil' , 'Kerman' , 34 , 'JR3GTTERJKD@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Soheil' , 'Qolami' , 'Gorgan' , 18 , 'DJghfueoij@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Akbar' , 'Ahmadi' , 'Semnan' , 26 , 'HUGHUGFYj@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Mohammad Hossein' , 'Lajevardi' , 'Karaj' , 30 , 'oiyfddej@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Ali' , 'Taqavi' , 'Tehran' , 55 , 'gujytyutiu@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Mahiar' , 'Rezaii' , 'Hamedan' , 25 , 'KLODJFtiu@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Amin' , 'Saadat' , 'Tehran' , 44 , 'ERGDTYJFTH@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Saman' , 'Alizade' , 'Kermanshah' , 31 , 'gHUYFT945@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Mahdi' , 'Abedi' , 'Yazd' , 29 , 'trnskhfuiu@GMAIL.COM')
INSERT INTO USERS(FIRSTNAME , LastName , CITY , AGE , EMAIL)
VALUES('Mohammad' , 'Karimi' , 'Tehran' , 19 , 'Frhhgue64@GMAIL.COM')
--ROLES------------------------------------------------------------------------------------
INSERT INTO ROLES(RoleName)
VALUES('PROGRAMER')
INSERT INTO ROLES(RoleName)
VALUES('MANAGER')
INSERT INTO ROLES(RoleName)
VALUES('DRIVER')
INSERT INTO ROLES(RoleName)
VALUES('CARPENTER')
INSERT INTO ROLES(RoleName)
VALUES('POET')
INSERT INTO ROLES(RoleName)
VALUES('PHOTOGRAOHER')
INSERT INTO ROLES(RoleName)
VALUES('PAINTER')
INSERT INTO ROLES(RoleName)
VALUES('BUILDING ENGINEER')
INSERT INTO ROLES(RoleName)
VALUES('MECHANIC')
INSERT INTO ROLES(RoleName)
VALUES('DIRECTOR')
INSERT INTO ROLES(RoleName)
VALUES('BOXER')
--USERS_ROLE-------------------------------------------------------------------------------
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(1,9)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(2,2)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(3,8)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(4,11)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(5,2)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(6,7)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(7,6)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(8,11)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(9,2)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(10,8)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(11,2)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(12,3)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(13,4)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(14,5)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(15,6)
INSERT INTO USER_ROLE(UserID , RoleID)
VALUES(16,1)
--DUTIES------------------------------------------------------------------------------------
INSERT INTO DUTIES(DutyName)
VALUES('Writing program')
INSERT INTO DUTIES(DutyName)
VALUES('Driving to the destination')
INSERT INTO DUTIES(DutyName)
VALUES('Making wooden items')
INSERT INTO DUTIES(DutyName)
VALUES('Writing poetry')
INSERT INTO DUTIES(DutyName)
VALUES('Taking photo')
INSERT INTO DUTIES(DutyName)
VALUES('Painting')
INSERT INTO DUTIES(DutyName)
VALUES('Building a building')
INSERT INTO DUTIES(DutyName)
VALUES('Car repairing')
INSERT INTO DUTIES(DutyName)
VALUES('Making movie')
INSERT INTO DUTIES(DutyName)
VALUES('Fighting')
--WORKSTATUS---------------------------------------------------------------------------------
INSERT INTO WORKSTATUS([Status])
VALUES('Completed')
INSERT INTO WORKSTATUS([Status])
VALUES('Not completed')
INSERT INTO WORKSTATUS([Status])
VALUES('Canceled')
INSERT INTO WORKSTATUS([Status])
VALUES('Postponed')
INSERT INTO WORKSTATUS([Status])
VALUES('It was done late')
--USERDUTY_DETAIL----------------------------------------------------------------------------
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(1 , 8 , 'Change the wheels of this car' , '2024-02-12   23:00:00' , '2024 -02 - 11   09: 05 : 00 ' ,900,1,2)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,BasicSalary,StatusID,ManagerID)
VALUES(3 , 7 , 'Build a villa near the sea' , '2023- 02- 19   00:00:00',   19000  , 2 ,5)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(4 , 10 , 'Win the tournament' , '2024 -04 -22   19 :18 :00  ' , '2024 -04 -22   19 :18  :00  ' ,   2000  , 1 ,9)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(6 , 6 , 'Draw Cristiano Ronaldo face in full detail' , '2024 -11 -03    00:00  :00  ' , '2024 -10 - 29   05:06  :00  ' ,1500, 1 , 9)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,BasicSalary,StatusID,ManagerID)
VALUES(7 , 5 , 'Take pictures of the scenery on the mountains of Iran' , '2024 -11 -02 00:00:00' ,1200 , 4 ,2)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(8 , 10 , 'Win the match against Tison' , '2024 -10 - 22   12: 15 :00  ' , '2024 - 10-22    12: 30 :00  ' ,  1250   , 2 ,11)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(10 , 7 , 'Build a five-story apartment with eight units' , '2026-05-12    00:00  :00  ' , '2026 -01 -10    14: 00 :00  ' ,  38000   ,1  , 5)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,BasicSalary,StatusID,ManagerID)
VALUES(12 , 2 , 'Deliver this package to Tehran and to the listed address' , '2022 - 04- 08   18:22:05  ',  250,3  , 9)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(13 , 3 , 'Make a double bed' , '2019 -02 -25    00:00:00  ' , '2022 -02 -25    00:00:00' ,  550   ,1  , 11)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(14 , 4 , 'Write a pop poem no longer than five minutes' , '2019 -09 -12    15:00  :00  ' , '2019 -11- 01   12:00  :00  ' , 440 , 5 , 2)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(15 , 5 , 'Take pictures of the wedding ceremony of these two people' , '2021 -03 -01    21: 00:00  ' , '2021 -03 -01    21: 00 :00  ' ,  800 , 1 , 11)
INSERT INTO USERDUTY_DETAIL(UserID,DutyID,MissionDetail,Agreed_FinishingTime,EndTime,BasicSalary,StatusID,ManagerID)
VALUES(16 , 1 , 'Write a program to describe nature to the deaf' , '2025 -02 -01    00:00  :00  ' , '2025 -06 -02    00: 00: 00 ' , 3800    , 5 ,5)
 
 SELECT * FROM USERS
 SELECT * FROM ROLES
 SELECT * FROM USER_ROLE
 SELECT * FROM DUTIES
 SELECT * FROM WORKSTATUS
 SELECT * FROM USERDUTY_DETAIL