EXEC GETALLUSERS
EXEC GETALLUSERSBYINDEX 'Hossein' , 'Rezaii' , 'HIUOHUYEM@GMAIL.COM'
EXEC ADDUSERS 'Mohammad Reza' , 'Golzar' , 'Tehran' , '30' , 'REZAGOLZAR73@GMAIL.COM'
EXEC UPDATEUSERS  @FNAME = 'Mohammad Hossein' ,@LNAME ='MohammadZade',@CITY = 'Mashhad' ,@AGE = 34 ,  @EMAIL ='WERFJOJOER@GMAIL.COM' , @ID =4
EXEC DELETEUSERS 5
-----
EXEC GETALLROLES
EXEC ADDROLES 'Pilot'
EXEC UPDATEROLES 'FIGHTER' , 11
EXEC DELETEROLES 4
-----
EXEC GETALLUSERROLE
EXEC GETALLUSERROLEBYID 2
EXEC ADDUSERROLE 202 ,10
EXEC UPDATEUSERROLE @USERID =202 , @ROLEID =  3
EXEC DELETEUSERROLE 202 ,3
-----
EXEC GETALLDUTIES
EXEC ADDDUTIES 'BRINGING THE PLANE TO ITS DESTINATION'
EXEC UPDATEDUTIES @ID= 9  , @NAME = 'Making movies and series' 
EXEC DELETEDUTIES 3
-----
EXEC GETALLWORKSTATUS 
EXEC ADDWORKSTATUS 'SEMI -FINISHED'
EXEC UPDATEWORKSTATUS  202 ,'HALF-BAKED'
EXEC DELETEWORKSTATUS 202
-----
EXEC GETALLUSERDUTYDETAIL
EXEC GETALLUSERDUTYDETAILBYID 1
EXEC ADDUSERDUTYDETAIL 1, 9 , 8 , 1 , 'Make my car red' , 1100 ,'2020-01-11 20:00:00' , '2020-01-01 19:00:00'
EXEC UPDATEUSERDUTYDETAIL @USERID = 7 , @MANAGERID = 2 , @DUTYID = 5 ,@STATUSID= 1 ,@DETAIL =  'Take pictures of the nature of Iran' ,@SALARY= 1000 ,  @FFINISHTIME ='2025-12-02 00:00:00' ,@ENDTIME = '2023-01-01 00:00:00'
EXEC DELETEUSERDUTYDETAIL 8 , 11


--SHOWING USER'S MISSON--
SELECT USERS.FirstName + '' + USERS.LastName , DUTIES.DutyName , WORKSTATUS.[Status] , USERDUTY_DETAIL.MissionDetail , USERDUTY_DETAIL.BasicSalary , USERDUTY_DETAIL.Agreed_FinishingTime , USERDUTY_DETAIL.EndTime
FROM USERDUTY_DETAIL 
JOIN USERS ON USERS.UserID =USERDUTY_DETAIL.UserID 
JOIN DUTIES ON DUTIES.DutyID = USERDUTY_DETAIL.DutyID
JOIN WORKSTATUS ON WORKSTATUS.StatusID = USERDUTY_DETAIL.StatusID
